cammie:
  blocked_names: [] # List of names that don't get shown
  blocked_ips: [] # List of IP's that don't get shown
  max_message_length: # Max message list
buzzer:
  pin: # PWM pin used by the buzzer
  song: # Options are - default
spotify:
  client_id: # Client ID of the Zeus spotify account
  client_secret: # Client secret of the Zeus spotify account
tap:
  url: # URL of tap
  beer: [] # List of beers in tap, can be found in tap
zess:
  url: # URL of zess
  day_amount: # Amount of days to keep track, should be the same as is displayed which depends on the screen size
