services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: scc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - scc_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  scc_data:
