// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventCreate = `-- name: EventCreate :one
INSERT INTO event (name, date, academic_year, location, poster)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type EventCreateParams struct {
	Name         string
	Date         pgtype.Timestamptz
	AcademicYear string
	Location     string
	Poster       []byte
}

func (q *Queries) EventCreate(ctx context.Context, arg EventCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, eventCreate,
		arg.Name,
		arg.Date,
		arg.AcademicYear,
		arg.Location,
		arg.Poster,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const eventDeleteAll = `-- name: EventDeleteAll :exec
DELETE FROM event
`

func (q *Queries) EventDeleteAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, eventDeleteAll)
	return err
}

const eventGetAllByCurrentYear = `-- name: EventGetAllByCurrentYear :many
SELECT id, name, date, academic_year, location, poster
FROM event
WHERE academic_year = (
    SELECT MAX(academic_year)
    FROM event
)
ORDER BY date ASC
`

func (q *Queries) EventGetAllByCurrentYear(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventGetAllByCurrentYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.AcademicYear,
			&i.Location,
			&i.Poster,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventGetAllByYear = `-- name: EventGetAllByYear :many
SELECT id, name, date, academic_year, location, poster
FROM event
WHERE academic_year = $1
`

func (q *Queries) EventGetAllByYear(ctx context.Context, academicYear string) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventGetAllByYear, academicYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.AcademicYear,
			&i.Location,
			&i.Poster,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
