// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gamification.sql

package sqlc

import (
	"context"
)

const gamificationCreate = `-- name: GamificationCreate :one
INSERT INTO gamification (name, score, avatar)
VALUES ($1, $2, $3)
RETURNING id
`

type GamificationCreateParams struct {
	Name   string
	Score  int32
	Avatar []byte
}

func (q *Queries) GamificationCreate(ctx context.Context, arg GamificationCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, gamificationCreate, arg.Name, arg.Score, arg.Avatar)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const gamificationDeleteAll = `-- name: GamificationDeleteAll :exec
DELETE FROM gamification
`

func (q *Queries) GamificationDeleteAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, gamificationDeleteAll)
	return err
}

const gamificationGetAll = `-- name: GamificationGetAll :many
SELECT id, name, score, avatar
FROM gamification
ORDER BY score DESC
`

func (q *Queries) GamificationGetAll(ctx context.Context) ([]Gamification, error) {
	rows, err := q.db.Query(ctx, gamificationGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gamification
	for rows.Next() {
		var i Gamification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Score,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
