// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TapCategory string

const (
	TapCategorySoft    TapCategory = "soft"
	TapCategoryMate    TapCategory = "mate"
	TapCategoryBeer    TapCategory = "beer"
	TapCategoryFood    TapCategory = "food"
	TapCategoryUnknown TapCategory = "unknown"
)

func (e *TapCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TapCategory(s)
	case string:
		*e = TapCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TapCategory: %T", src)
	}
	return nil
}

type NullTapCategory struct {
	TapCategory TapCategory
	Valid       bool // Valid is true if TapCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTapCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TapCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TapCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTapCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TapCategory), nil
}

type Event struct {
	ID           int32
	Name         string
	Date         pgtype.Timestamptz
	AcademicYear string
	Location     string
	Poster       []byte
}

type Gamification struct {
	ID     int32
	Name   string
	Score  int32
	Avatar []byte
}

type Message struct {
	ID        int32
	Name      string
	Ip        string
	Message   string
	CreatedAt pgtype.Timestamptz
}

type Scan struct {
	ID       int32
	ScanTime pgtype.Timestamptz
	ScanID   int32
}

type Season struct {
	ID      int32
	Name    string
	Start   pgtype.Timestamp
	End     pgtype.Timestamp
	Current bool
}

type Song struct {
	ID         int32
	Title      string
	SpotifyID  string
	DurationMs int32
	Album      string
	LyricsType pgtype.Text
	Lyrics     pgtype.Text
}

type SongArtist struct {
	ID         int32
	Name       string
	SpotifyID  string
	Followers  int32
	Popularity int32
}

type SongArtistGenre struct {
	ID       int32
	ArtistID int32
	GenreID  int32
}

type SongArtistSong struct {
	ID       int32
	ArtistID int32
	SongID   int32
}

type SongGenre struct {
	ID    int32
	Genre string
}

type SongHistory struct {
	ID        int32
	SongID    int32
	CreatedAt pgtype.Timestamptz
}

type Tap struct {
	ID             int32
	OrderID        int32
	OrderCreatedAt pgtype.Timestamptz
	Name           string
	CreatedAt      pgtype.Timestamptz
	Category       TapCategory
}
