// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: season.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const seasonCreate = `-- name: SeasonCreate :one
INSERT INTO season (name, start, "end", current)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type SeasonCreateParams struct {
	Name    string
	Start   pgtype.Timestamp
	End     pgtype.Timestamp
	Current bool
}

func (q *Queries) SeasonCreate(ctx context.Context, arg SeasonCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, seasonCreate,
		arg.Name,
		arg.Start,
		arg.End,
		arg.Current,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const seasonDeleteAll = `-- name: SeasonDeleteAll :exec
DELETE FROM season
`

func (q *Queries) SeasonDeleteAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seasonDeleteAll)
	return err
}

const seasonGetAll = `-- name: SeasonGetAll :many
SELECT id, name, start, "end", current
FROM season
`

func (q *Queries) SeasonGetAll(ctx context.Context) ([]Season, error) {
	rows, err := q.db.Query(ctx, seasonGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Start,
			&i.End,
			&i.Current,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonGetCurrent = `-- name: SeasonGetCurrent :one
SELECT id, name, start, "end", current
FROM season
WHERE current = true
`

func (q *Queries) SeasonGetCurrent(ctx context.Context) (Season, error) {
	row := q.db.QueryRow(ctx, seasonGetCurrent)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.End,
		&i.Current,
	)
	return i, err
}

const seasonUpdate = `-- name: SeasonUpdate :exec
UPDATE season
SET name = $1, start = $2, "end" = $3, current = $4
WHERE id = $5
RETURNING id, name, start, "end", current
`

type SeasonUpdateParams struct {
	Name    string
	Start   pgtype.Timestamp
	End     pgtype.Timestamp
	Current bool
	ID      int32
}

func (q *Queries) SeasonUpdate(ctx context.Context, arg SeasonUpdateParams) error {
	_, err := q.db.Exec(ctx, seasonUpdate,
		arg.Name,
		arg.Start,
		arg.End,
		arg.Current,
		arg.ID,
	)
	return err
}
