// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tap.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const tapCreate = `-- name: TapCreate :one
INSERT INTO tap (order_id, order_created_at, name, category)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type TapCreateParams struct {
	OrderID        int32
	OrderCreatedAt pgtype.Timestamptz
	Name           string
	Category       TapCategory
}

func (q *Queries) TapCreate(ctx context.Context, arg TapCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, tapCreate,
		arg.OrderID,
		arg.OrderCreatedAt,
		arg.Name,
		arg.Category,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const tapGetCountByCategory = `-- name: TapGetCountByCategory :many
SELECT category, COUNT(*), MAX(order_created_at)::TIMESTAMP AS latest_order_created_at
FROM tap
GROUP BY category
`

type TapGetCountByCategoryRow struct {
	Category             TapCategory
	Count                int64
	LatestOrderCreatedAt pgtype.Timestamp
}

func (q *Queries) TapGetCountByCategory(ctx context.Context) ([]TapGetCountByCategoryRow, error) {
	rows, err := q.db.Query(ctx, tapGetCountByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TapGetCountByCategoryRow
	for rows.Next() {
		var i TapGetCountByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count, &i.LatestOrderCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tapGetLast = `-- name: TapGetLast :one
SELECT id, order_id, order_created_at, name, created_at, category
FROM tap
ORDER BY order_id DESC
LIMIT 1
`

func (q *Queries) TapGetLast(ctx context.Context) (Tap, error) {
	row := q.db.QueryRow(ctx, tapGetLast)
	var i Tap
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderCreatedAt,
		&i.Name,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}
