[server]
host = "localhost"
port = 3000

[spotify]
client_id = "your_client_id"
client_secret = "your_client_secret"

[tap]
api = "https://tap.zeus.gent"
interval_s = 60
beers = [
	"Schelfaut",
	"Duvel",
	"Fourchette",
	"Jupiler",
	"Karmeliet",
	"Kriek",
	"Chouffe",
	"Maes",
	"Somersby",
	"Sportzot",
	"Stella",
]

[zess]
api = "http://localhost:4000/api"
interval_season_s = 300
interval_scan_s = 60

[buzzer]
song = [
    "-n", "-f880", "-l100", "-d0",
	"-n", "-f988", "-l100", "-d0",
	"-n", "-f588", "-l100", "-d0",
	"-n", "-f989", "-l100", "-d0",
	"-n", "-f660", "-l200", "-d0",
	"-n", "-f660", "-l200", "-d0",
	"-n", "-f588", "-l100", "-d0",
	"-n", "-f555", "-l100", "-d0",
	"-n", "-f495", "-l100", "-d0",
]

[tui]

[tui.zess]
weeks = 10
interval_scan_s = 60
interval_season_s = 3600

[tui.message]
interval_s = 1

[tui.tap]
interval_s = 60
