// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: message.sql

package sqlc

import (
	"context"
)

const messageCreate = `-- name: MessageCreate :one
INSERT INTO message (name, ip, message)
VALUES ($1, $2, $3)
RETURNING id
`

type MessageCreateParams struct {
	Name    string
	Ip      string
	Message string
}

func (q *Queries) MessageCreate(ctx context.Context, arg MessageCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, messageCreate, arg.Name, arg.Ip, arg.Message)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const messageGetSinceID = `-- name: MessageGetSinceID :many
SELECT id, name, ip, message, created_at
FROM message
WHERE id > $1
ORDER BY created_at ASC
`

func (q *Queries) MessageGetSinceID(ctx context.Context, id int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, messageGetSinceID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
