// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reply.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const replyCreate = `-- name: ReplyCreate :one
INSERT INTO reply (message_id, name, message)
VALUES ($1, $2, $3)
RETURNING id
`

type ReplyCreateParams struct {
	MessageID int32
	Name      pgtype.Text
	Message   string
}

func (q *Queries) ReplyCreate(ctx context.Context, arg ReplyCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, replyCreate, arg.MessageID, arg.Name, arg.Message)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const replyGetSinceMessageID = `-- name: ReplyGetSinceMessageID :many
SELECT id, message_id, name, message, created_at
FROM reply
WHERE message_id >= $1
ORDER BY message_id
`

func (q *Queries) ReplyGetSinceMessageID(ctx context.Context, messageID int32) ([]Reply, error) {
	rows, err := q.db.Query(ctx, replyGetSinceMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reply
	for rows.Next() {
		var i Reply
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Name,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
