// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scan.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const scanCreate = `-- name: ScanCreate :one
INSERT INTO scan (scan_id, scan_time)
VALUES ($1, $2)
RETURNING id
`

type ScanCreateParams struct {
	ScanID   int32
	ScanTime pgtype.Timestamptz
}

func (q *Queries) ScanCreate(ctx context.Context, arg ScanCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, scanCreate, arg.ScanID, arg.ScanTime)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const scanGetAllSinceID = `-- name: ScanGetAllSinceID :many
SELECT id, scan_time, scan_id
FROM scan
WHERE id > $1
ORDER BY scan_id, scan_time ASC
`

func (q *Queries) ScanGetAllSinceID(ctx context.Context, id int32) ([]Scan, error) {
	rows, err := q.db.Query(ctx, scanGetAllSinceID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(&i.ID, &i.ScanTime, &i.ScanID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanGetInSeason = `-- name: ScanGetInSeason :many
SELECT sc.id, sc.scan_time, sc.scan_id
FROM scan sc
LEFT JOIN season se ON se.start <= sc.scan_time AND sc.scan_time < se.end
WHERE se.id = $1
ORDER BY sc.scan_time ASC
`

func (q *Queries) ScanGetInSeason(ctx context.Context, id int32) ([]Scan, error) {
	rows, err := q.db.Query(ctx, scanGetInSeason, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(&i.ID, &i.ScanTime, &i.ScanID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanGetLast = `-- name: ScanGetLast :one
SELECT id, scan_time, scan_id
FROM scan
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) ScanGetLast(ctx context.Context) (Scan, error) {
	row := q.db.QueryRow(ctx, scanGetLast)
	var i Scan
	err := row.Scan(&i.ID, &i.ScanTime, &i.ScanID)
	return i, err
}
