// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: song.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const songArtistCreate = `-- name: SongArtistCreate :one
INSERT INTO song_artist (name, spotify_id)
VALUES ($1, $2)
RETURNING id
`

type SongArtistCreateParams struct {
	Name      string
	SpotifyID string
}

func (q *Queries) SongArtistCreate(ctx context.Context, arg SongArtistCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, songArtistCreate, arg.Name, arg.SpotifyID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const songArtistGenreCreate = `-- name: SongArtistGenreCreate :one
INSERT INTO song_artist_genre (artist_id, genre_id)
VALUES ($1, $2)
RETURNING id
`

type SongArtistGenreCreateParams struct {
	ArtistID int32
	GenreID  int32
}

func (q *Queries) SongArtistGenreCreate(ctx context.Context, arg SongArtistGenreCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, songArtistGenreCreate, arg.ArtistID, arg.GenreID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const songArtistGetBySpotify = `-- name: SongArtistGetBySpotify :one
SELECT id, name, spotify_id
FROM song_artist
WHERE spotify_id = $1
`

func (q *Queries) SongArtistGetBySpotify(ctx context.Context, spotifyID string) (SongArtist, error) {
	row := q.db.QueryRow(ctx, songArtistGetBySpotify, spotifyID)
	var i SongArtist
	err := row.Scan(&i.ID, &i.Name, &i.SpotifyID)
	return i, err
}

const songArtistGetBySpotifyIds = `-- name: SongArtistGetBySpotifyIds :many
SELECT a.id, a.name, a.spotify_id, g.id, g.genre
FROM song_artist a
LEFT JOIN song_genre g ON a.id = g.artist_id
WHERE a.spotify_id = ANY($1::text[])
`

type SongArtistGetBySpotifyIdsRow struct {
	SongArtist SongArtist
	SongGenre  SongGenre
}

func (q *Queries) SongArtistGetBySpotifyIds(ctx context.Context, dollar_1 []string) ([]SongArtistGetBySpotifyIdsRow, error) {
	rows, err := q.db.Query(ctx, songArtistGetBySpotifyIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SongArtistGetBySpotifyIdsRow
	for rows.Next() {
		var i SongArtistGetBySpotifyIdsRow
		if err := rows.Scan(
			&i.SongArtist.ID,
			&i.SongArtist.Name,
			&i.SongArtist.SpotifyID,
			&i.SongGenre.ID,
			&i.SongGenre.Genre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const songArtistSongCreate = `-- name: SongArtistSongCreate :one
INSERT INTO song_artist_song (artist_id, song_id)
VALUES ($1, $2)
RETURNING id
`

type SongArtistSongCreateParams struct {
	ArtistID int32
	SongID   int32
}

func (q *Queries) SongArtistSongCreate(ctx context.Context, arg SongArtistSongCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, songArtistSongCreate, arg.ArtistID, arg.SongID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const songCreate = `-- name: SongCreate :one
INSERT INTO song (title, album, spotify_id, duration_ms, lyrics_type, lyrics)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type SongCreateParams struct {
	Title      string
	Album      string
	SpotifyID  string
	DurationMs int32
	LyricsType LyricsTypeEnum
	Lyrics     pgtype.Text
}

func (q *Queries) SongCreate(ctx context.Context, arg SongCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, songCreate,
		arg.Title,
		arg.Album,
		arg.SpotifyID,
		arg.DurationMs,
		arg.LyricsType,
		arg.Lyrics,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const songGenreCreate = `-- name: SongGenreCreate :one
INSERT INTO song_genre (genre)
VALUES ($1)
RETURNING id
`

func (q *Queries) SongGenreCreate(ctx context.Context, genre string) (int32, error) {
	row := q.db.QueryRow(ctx, songGenreCreate, genre)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const songGenreGetByGenre = `-- name: SongGenreGetByGenre :one
SELECT id, genre
FROM song_genre
WHERE genre = $1
`

func (q *Queries) SongGenreGetByGenre(ctx context.Context, genre string) (SongGenre, error) {
	row := q.db.QueryRow(ctx, songGenreGetByGenre, genre)
	var i SongGenre
	err := row.Scan(&i.ID, &i.Genre)
	return i, err
}

const songGetBySpotify = `-- name: SongGetBySpotify :one
SELECT id, title, spotify_id, duration_ms, album, lyrics, lyrics_type
FROM song
WHERE spotify_id = $1
`

func (q *Queries) SongGetBySpotify(ctx context.Context, spotifyID string) (Song, error) {
	row := q.db.QueryRow(ctx, songGetBySpotify, spotifyID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SpotifyID,
		&i.DurationMs,
		&i.Album,
		&i.Lyrics,
		&i.LyricsType,
	)
	return i, err
}

const songHistoryCreate = `-- name: SongHistoryCreate :one
INSERT INTO song_history (song_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) SongHistoryCreate(ctx context.Context, songID int32) (int32, error) {
	row := q.db.QueryRow(ctx, songHistoryCreate, songID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
