// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gamification.sql

package sqlc

import (
	"context"
)

const createGamification = `-- name: CreateGamification :one
INSERT INTO gamification (name, score, avatar)
VALUES (?, ?, ?)
RETURNING id, name, score, avatar
`

type CreateGamificationParams struct {
	Name   string
	Score  int64
	Avatar string
}

func (q *Queries) CreateGamification(ctx context.Context, arg CreateGamificationParams) (Gamification, error) {
	row := q.db.QueryRowContext(ctx, createGamification, arg.Name, arg.Score, arg.Avatar)
	var i Gamification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Score,
		&i.Avatar,
	)
	return i, err
}

const deleteGamification = `-- name: DeleteGamification :execrows
DELETE FROM gamification
WHERE id = ?
`

func (q *Queries) DeleteGamification(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGamification, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllGamification = `-- name: GetAllGamification :many

SELECT id, name, score, avatar
FROM gamification
`

// CRUD
func (q *Queries) GetAllGamification(ctx context.Context) ([]Gamification, error) {
	rows, err := q.db.QueryContext(ctx, getAllGamification)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gamification
	for rows.Next() {
		var i Gamification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Score,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGamificationByScore = `-- name: GetAllGamificationByScore :many
SELECT id, name, score, avatar
FROM gamification
ORDER BY score DESC
`

func (q *Queries) GetAllGamificationByScore(ctx context.Context) ([]Gamification, error) {
	rows, err := q.db.QueryContext(ctx, getAllGamificationByScore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gamification
	for rows.Next() {
		var i Gamification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Score,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGamificationScore = `-- name: UpdateGamificationScore :one


UPDATE gamification
SET score = ?
WHERE id = ?
RETURNING id, name, score, avatar
`

type UpdateGamificationScoreParams struct {
	Score int64
	ID    int64
}

// Other
func (q *Queries) UpdateGamificationScore(ctx context.Context, arg UpdateGamificationScoreParams) (Gamification, error) {
	row := q.db.QueryRowContext(ctx, updateGamificationScore, arg.Score, arg.ID)
	var i Gamification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Score,
		&i.Avatar,
	)
	return i, err
}
