// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: season.sql

package sqlc

import (
	"context"
	"time"
)

const createSeason = `-- name: CreateSeason :one
INSERT INTO season (name, start, end)
VALUES (?, ?, ?)
RETURNING id, name, start, "end"
`

type CreateSeasonParams struct {
	Name  string
	Start time.Time
	End   time.Time
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, createSeason, arg.Name, arg.Start, arg.End)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.End,
	)
	return i, err
}

const deleteSeason = `-- name: DeleteSeason :execrows
DELETE FROM season
WHERE id = ?
`

func (q *Queries) DeleteSeason(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSeason, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllSeasons = `-- name: GetAllSeasons :many

SELECT id, name, start, "end"
FROM season
`

// CRUD
func (q *Queries) GetAllSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getAllSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Start,
			&i.End,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, name, start, "end"
FROM season
WHERE id = ?
`

func (q *Queries) GetSeasonByID(ctx context.Context, id int64) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.End,
	)
	return i, err
}

const updateSeason = `-- name: UpdateSeason :one
UPDATE season
SET name = ?, start = ?, end = ?
WHERE id = ?
RETURNING id, name, start, "end"
`

type UpdateSeasonParams struct {
	Name  string
	Start time.Time
	End   time.Time
	ID    int64
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, updateSeason,
		arg.Name,
		arg.Start,
		arg.End,
		arg.ID,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.End,
	)
	return i, err
}
